FROM node:22-bookworm-slim

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile
COPY . /app/
RUN npx prisma generate

EXPOSE 8080

CMD ["pnpm", "run", "dev"]