AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.0
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 300

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 50
