// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String webApiKey = String.fromEnvironment(
    'WEB_API_KEY',
    defaultValue: '',
  );

  static const String androidApiKey = String.fromEnvironment(
    'ANDROID_API_KEY',
    defaultValue: '',
  );

  static const String iosApiKey = String.fromEnvironment(
    'IOS_API_KEY',
    defaultValue: '',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: webApiKey,
    appId: '1:422364792408:web:703741af167489b80b2c2d',
    messagingSenderId: '422364792408',
    projectId: 'numeric-skill-460414-d3',
    authDomain: 'numeric-skill-460414-d3.firebaseapp.com',
    storageBucket: 'numeric-skill-460414-d3.firebasestorage.app',
    measurementId: 'G-Q5GDVMX2L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: androidApiKey,
    appId: '1:422364792408:android:d5bbb68d3371e0440b2c2d',
    messagingSenderId: '422364792408',
    projectId: 'numeric-skill-460414-d3',
    storageBucket: 'numeric-skill-460414-d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: iosApiKey,
    appId: '1:422364792408:ios:2d206118132d81aa0b2c2d',
    messagingSenderId: '422364792408',
    projectId: 'numeric-skill-460414-d3',
    storageBucket: 'numeric-skill-460414-d3.firebasestorage.app',
    iosClientId:
        '422364792408-a7jdosv1m1gloa89b34gaurqj2t62rf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
