name: 🚀 [Deploy][WEB] Frontend to Firebase Hosting

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

env:
  FIREBASE_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  FLUTTER_VERSION: '3.29.3'
  BUILD_BASE_HREF: /
  WEB_RENDERER: 'false' # FLUTTER_WEB_USE_SKIA
  API_BASE_URL: ${{ vars.API_BASE_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Setup Flutter Dependencies
        run: flutter pub get

      # - name: Run Tests
      #   run: flutter test

      - name: Build Web
        run: |
          flutter build web \
            --release \
            --base-href ${{ env.BUILD_BASE_HREF }} \
            --dart-define=FLUTTER_WEB_USE_SKIA=${{ env.WEB_RENDERER }} \
            --dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/ \
            --dart-define=API_BASE_URL=${{ env.API_BASE_URL }}

      # - name: Deploy to Firebase Hosting (Preview)
      #   if: github.event_name == 'pull_request'
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      #     projectId: ${{ env.FIREBASE_PROJECT_ID }}
      #     entryPoint: ./frontend

      - name: Deploy to Firebase Hosting (Production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
          target: production
          entryPoint: ./frontend

      # - name: Deploy to Firebase Hosting (Staging)
      #   if: github.ref == 'refs/heads/develop'
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      #     channelId: staging
      #     projectId: ${{ env.FIREBASE_PROJECT_ID }}
      #     entryPoint: ./frontend
